version: '3.4'

services:
  unqmeterapi:
    image: ${DOCKER_REGISTRY-}unqmeterapi
    environment:
        - ConnectionStrings__sqlConnection=server=db; database=UNQ_METER; User Id=sa; pwd=Unqmeter123*
    build:
      context: .
      dockerfile: UnqMeterAPI/Dockerfile
    ports:
        - 7054:443
    depends_on:
        - db
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
        SA_PASSWORD: "Unqmeter123*"
        ACCEPT_EULA: "Y"
    ports:
        - "14433:1433"