name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file UnqMeterAPI/Dockerfile --tag dockerfile:$(date +%s)
    
    - name: Restore dependencies
      run: | 
        cd UnqMeterAPI.Test
        dotnet restore
      
    - name: Build
      run: |
        cd UnqMeterAPI.Test
        dotnet build --no-restore /p:ContinuousIntegrationBuild=true
      
    - name: Test
      run: |
        cd UnqMeterAPI.Test
        dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:ExcludeByFile=\"**/*Migrations/*.cs"
      
    - name: Codecov
      uses: codecov/codecov-action@v3
