name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file UnqMeterAPI/Dockerfile --tag dockerfile:$(date +%s)
    
    - name: Install Required Tools
      run: |
        dotnet new tool-manifest
        dotnet tool install dotnet-reportgenerator-globaltool
        dotnet tool install dotnet-coverage

    - name: Run the unit tests with code coverage
      run: dotnet coverage collect dotnet test --output ./Tests/CodeCoverage --output-format cobertura

    - name: Generate Report
      run: |
        dotnet reportgenerator -reports:./Tests/CodeCoverage.cobertura.xml -targetdir:"./Tests/CoverageReport" -reporttypes:Html -assemblyfilters:+UnqMeterAPI
